import { api } from '@/api/client';
import * as E from '@/api/endpoints';
import { mapUsers, mapProducts, mapOrders, mapClients, mapKpis } from '@/mappers';

function get(ep, params) { return api.get(ep(), { params }); }
function getById(ep, id, params) { return api.get(ep(id), { params }); }
function post(ep, data) { return api.post(ep(), data); }
function put(ep, id, data) { return api.put(ep(id), data); }
function del(ep, id) { return api.delete(ep(id)); }

export const authRepository = { login: (e, p) => post(E.AuthEndpoints.login, { email: e, password: p }), getProfile: () => get(E.AuthEndpoints.me) };
export const iamRepository = { getUsers: async (q) => mapUsers(await get(E.IamEndpoints.users, q)), getUser: (id) => getById(E.IamEndpoints.userById, id), createUser: (d) => post(E.IamEndpoints.users, d), updateUser: (id, d) => put(E.IamEndpoints.userById, id, d), deleteUser: (id) => del(E.IamEndpoints.userById, id), updateStatus: (id, d) => put(E.IamEndpoints.userStatus, id, d), getRoles: () => get(E.IamEndpoints.roles), createRole: (d) => post(E.IamEndpoints.roles, d), updateRole: (id, d) => put(E.IamEndpoints.roleById, id, d), deleteRole: (id) => del(E.IamEndpoints.roleById, id), getPermissions: () => get(E.IamEndpoints.permissions), saveMatrix: (d) => put(E.IamEndpoints.permissionMatrix, null, d) };
export const catalogRepository = { getProducts: async (q) => { const raw = await get(E.CatalogEndpoints.products, q); const data = mapProducts(raw); const meta = raw?.meta || { total: data.length, page: 1, perPage: 25 }; return { data, meta }; }, getProduct: (id) => getById(E.CatalogEndpoints.productById, id), createProduct: (d) => post(E.CatalogEndpoints.products, d), updateProduct: (id, d) => put(E.CatalogEndpoints.productById, id, d), deleteProduct: (id) => del(E.CatalogEndpoints.productById, id), getVariants: (q) => get(E.CatalogEndpoints.variants, q), createVariant: (d) => post(E.CatalogEndpoints.variants, d), updateVariant: (id, d) => put(E.CatalogEndpoints.variantById, id, d), deleteVariant: (id) => del(E.CatalogEndpoints.variantById, id), addMedia: (id, d) => post(E.CatalogEndpoints.productMedia, id, d), getCategories: () => get(E.CatalogEndpoints.categories), getCollections: () => get(E.CatalogEndpoints.collections) };
export const ordersRepository = { getAll: async (q) => mapOrders(await get(E.OrdersEndpoints.orders, q)), getById: (id) => getById(E.OrdersEndpoints.orderById, id), create: (d) => post(E.OrdersEndpoints.orders, d), updateStatus: (id, d) => put(E.OrdersEndpoints.orderStatus, id, d), addNote: (id, d) => post(E.OrdersEndpoints.orderNotes, id, d), getEvents: (id) => getById(E.OrdersEndpoints.orderEvents, id) };
export const paymentsRepository = { getAll: (q) => get(E.PaymentsEndpoints.transactions, q), createIntent: (d) => post(E.PaymentsEndpoints.createIntent, d), refund: (id, d) => post(E.PaymentsEndpoints.refund, id, d) };
export const inventoryRepository = { getStock: (q) => get(E.InventoryEndpoints.stock, q), adjust: (id, d) => post(E.InventoryEndpoints.adjust, id, d), getMovements: (q) => get(E.InventoryEndpoints.movements, q), getTransfers: (q) => get(E.InventoryEndpoints.transfers, q) };
export const logisticsRepository = { getShipments: (q) => get(E.LogisticsEndpoints.shipments, q), createShipment: (d) => post(E.LogisticsEndpoints.shipments, d), updateStatus: (id, d) => put(E.LogisticsEndpoints.shipmentStatus, id, d), getCarriers: () => get(E.LogisticsEndpoints.carriers) };
export const marketingRepository = { getCampaigns: (q) => get(E.MarketingEndpoints.campaigns, q), getCampaign: (id) => getById(E.MarketingEndpoints.campaignById, id), createCampaign: (d) => post(E.MarketingEndpoints.campaigns, d), updateCampaign: (id, d) => put(E.MarketingEndpoints.campaignById, id, d), deleteCampaign: (id) => del(E.MarketingEndpoints.campaignById, id), getCoupons: () => get(E.MarketingEndpoints.coupons), getCoupon: (id) => getById(E.MarketingEndpoints.couponById, id), createCoupon: (d) => post(E.MarketingEndpoints.coupons, d), updateCoupon: (id, d) => put(E.MarketingEndpoints.couponById, id, d), deleteCoupon: (id) => del(E.MarketingEndpoints.couponById, id), getPromotions: () => get(E.MarketingEndpoints.promotions), getPromotion: (id) => getById(E.MarketingEndpoints.promotionById, id), createPromotion: (d) => post(E.MarketingEndpoints.promotions, d), updatePromotion: (id, d) => put(E.MarketingEndpoints.promotionById, id, d), deletePromotion: (id) => del(E.MarketingEndpoints.promotionById, id) };
export const cmsRepository = { getContents: (q) => get(E.CmsEndpoints.contents, q), getContent: (id) => getById(E.CmsEndpoints.contentById, id), createContent: (d) => post(E.CmsEndpoints.contents, d), updateContent: (id, d) => put(E.CmsEndpoints.contentById, id, d), deleteContent: (id) => del(E.CmsEndpoints.contentById, id), getHeroSlides: () => get(E.CmsEndpoints.heroSlides), createHeroSlide: (d) => post(E.CmsEndpoints.heroSlides, d), updateHeroSlide: (id, d) => put(E.CmsEndpoints.heroSlideById, id, d), deleteHeroSlide: (id) => del(E.CmsEndpoints.heroSlideById, id), getGallery: () => get(E.CmsEndpoints.gallery), createGallery: (d) => post(E.CmsEndpoints.gallery, d), updateGallery: (id, d) => put(E.CmsEndpoints.galleryById, id, d), deleteGallery: (id) => del(E.CmsEndpoints.galleryById, id), getTestimonials: () => get(E.CmsEndpoints.testimonials), createTestimonial: (d) => post(E.CmsEndpoints.testimonials, d), updateTestimonial: (id, d) => put(E.CmsEndpoints.testimonialById, id, d), deleteTestimonial: (id) => del(E.CmsEndpoints.testimonialById, id), getBenefits: () => get(E.CmsEndpoints.benefits), createBenefit: (d) => post(E.CmsEndpoints.benefits, d), updateBenefit: (id, d) => put(E.CmsEndpoints.benefitById, id, d), deleteBenefit: (id) => del(E.CmsEndpoints.benefitById, id), getArtisanProcesses: () => get(E.CmsEndpoints.artisanProcesses), createArtisanProcess: (d) => post(E.CmsEndpoints.artisanProcesses, d), updateArtisanProcess: (id, d) => put(E.CmsEndpoints.artisanProcessById, id, d), deleteArtisanProcess: (id) => del(E.CmsEndpoints.artisanProcessById, id) };
export const settingsRepository = { getCompany: () => get(E.SettingsEndpoints.company), updateCompany: (d) => put(E.SettingsEndpoints.company, null, d) };
export const analyticsRepository = { getKpis: async () => mapKpis(await get(E.AnalyticsEndpoints.kpis)) };
export const auditRepository = { getLogs: (q) => get(E.AuditEndpoints.logs, q) };
export const crmRepository = { getClients: async (q) => mapClients(await get(E.CrmEndpoints.clients, q)), getClient: (id) => getById(E.CrmEndpoints.clientById, id), createClient: (d) => post(E.CrmEndpoints.clients, d), updateClient: (id, d) => put(E.CrmEndpoints.clientById, id, d), addNote: (id, d) => post(E.CrmEndpoints.clientNotes, id, d) };
export const textileRepository = { getMaterials: () => get(E.TextileEndpoints.materials), getColors: () => get(E.TextileEndpoints.colors), getSizes: () => get(E.TextileEndpoints.sizes), getSeasons: () => get(E.TextileEndpoints.seasons) };
export const storageRepository = { upload: (f) => { const fd = new FormData(); fd.append('file', f); return api.post(E.StorageEndpoints.upload(), fd, { headers: { 'Content-Type': 'multipart/form-data' } }); }, uploadPublic: (f) => { const fd = new FormData(); fd.append('file', f); return api.post(E.StorageEndpoints.uploadPublic(), fd, { headers: { 'Content-Type': 'multipart/form-data' } }); }, delete: (k) => api.delete(E.StorageEndpoints.delete(k)) };

