export function createUser(raw) { if (!raw) return null; return { id: raw.id, name: raw.name, email: raw.email, role: raw.role?.name || raw.role || '', phone: raw.phone || '', status: raw.status || 'active', createdAt: raw.createdAt }; }
export function createRole(raw) { if (!raw) return null; return { id: raw.id, name: raw.name, category: raw.category || '', status: raw.status || 'active' }; }
export function createPermission(raw) { if (!raw) return null; return { id: raw.id, module: raw.module, action: raw.action, name: raw.name }; }
export function createProduct(raw) { if (!raw) return null; return { id: raw.id, sku: raw.sku, name: raw.name, price: raw.price || 0, status: raw.status || 'draft', categoryId: raw.categoryId, image: raw.image || '', stock: raw.stock || 0, createdAt: raw.createdAt }; }
export function createOrder(raw) { if (!raw) return null; return { id: raw.id, orderNumber: raw.orderNumber, customerId: raw.customerId, status: raw.status || 'pending', subtotal: raw.subtotal || 0, total: raw.total || 0, paid: raw.paid || false, items: (raw.items || []).map(i => ({ id: i.id, productName: i.productName, sku: i.sku, quantity: i.quantity, unitPrice: i.unitPrice })), createdAt: raw.createdAt }; }
export function createClient(raw) { if (!raw) return null; return { id: raw.id, name: raw.name, company: raw.company || '', email: raw.email, type: raw.type || 'retail', status: raw.status || 'active', phone: raw.phone || '', createdAt: raw.createdAt }; }
export function createCampaign(raw) { if (!raw) return null; return { id: raw.id, name: raw.name, type: raw.type || '', status: raw.status || 'draft', budget: raw.budget || 0, channel: raw.channel || '', createdAt: raw.createdAt }; }
export function createContent(raw) { if (!raw) return null; return { id: raw.id, title: raw.title, slug: raw.slug, type: raw.type || 'page', status: raw.status || 'draft', authorId: raw.authorId, publishedAt: raw.publishedAt, createdAt: raw.createdAt }; }
export function createStockItem(raw) { if (!raw) return null; return { id: raw.id, productId: raw.productId, variantId: raw.variantId, warehouseId: raw.warehouseId, quantity: raw.quantity || 0, reserved: raw.reserved || 0, minStock: raw.minStock || 0 }; }
export function createTransaction(raw) { if (!raw) return null; return { id: raw.id, transactionId: raw.transactionId, orderId: raw.orderId, method: raw.method || '', amount: raw.amount || 0, status: raw.status || 'pending', currency: raw.currency || 'PEN', createdAt: raw.createdAt }; }
export function createShipment(raw) { if (!raw) return null; return { id: raw.id, waybill: raw.waybill, orderId: raw.orderId, carrier: raw.carrier, status: raw.status || 'pending', originCity: raw.originCity || '', destinationCity: raw.destinationCity || '', createdAt: raw.createdAt }; }
export function createAuditLog(raw) { if (!raw) return null; return { id: raw.id, userId: raw.userId, action: raw.action, module: raw.module, description: raw.description || '', severity: raw.severity || 'info', ipAddress: raw.ipAddress || '', createdAt: raw.createdAt }; }
export function createCompanySetting(raw) { if (!raw) return null; return { id: raw.id, legalName: raw.legalName, taxId: raw.taxId, email: raw.email, phone: raw.phone || '', address: raw.address || '', website: raw.website || '', currency: raw.primaryCurrency || 'PEN' }; }
