import * as R from '@/repositories/api';

export class IamService { constructor(r) { this.r = r; } getUsers(q) { return this.r.getUsers(q); } getUser(id) { return this.r.getUser(id); } createUser(d) { return this.r.createUser(d); } updateUser(id, d) { return this.r.updateUser(id, d); } deleteUser(id) { return this.r.deleteUser(id); } updateStatus(id, d) { return this.r.updateStatus(id, d); } getRoles() { return this.r.getRoles(); } createRole(d) { return this.r.createRole(d); } updateRole(id, d) { return this.r.updateRole(id, d); } deleteRole(id) { return this.r.deleteRole(id); } getPermissions() { return this.r.getPermissions(); } saveMatrix(d) { return this.r.saveMatrix(d); } }
export class CatalogService { constructor(r) { this.r = r; } getProducts(q) { return this.r.getProducts(q); } getProduct(id) { return this.r.getProduct(id); } createProduct(d) { return this.r.createProduct(d); } updateProduct(id, d) { return this.r.updateProduct(id, d); } deleteProduct(id) { return this.r.deleteProduct(id); } getCategories() { return this.r.getCategories(); } getCollections() { return this.r.getCollections(); } }
export class OrdersService { constructor(r) { this.r = r; } getAll(q) { return this.r.getAll(q); } getById(id) { return this.r.getById(id); } create(d) { return this.r.create(d); } updateStatus(id, d) { return this.r.updateStatus(id, d); } addNote(id, d) { return this.r.addNote(id, d); } getEvents(id) { return this.r.getEvents(id); } }
export class PaymentsService { constructor(r) { this.r = r; } getAll(q) { return this.r.getAll(q); } createIntent(d) { return this.r.createIntent(d); } refund(id, d) { return this.r.refund(id, d); } }
export class InventoryService { constructor(r) { this.r = r; } getStock(q) { return this.r.getStock(q); } adjust(id, d) { return this.r.adjust(id, d); } getMovements(q) { return this.r.getMovements(q); } getTransfers(q) { return this.r.getTransfers(q); } }
export class LogisticsService { constructor(r) { this.r = r; } getShipments(q) { return this.r.getShipments(q); } createShipment(d) { return this.r.createShipment(d); } updateStatus(id, d) { return this.r.updateStatus(id, d); } getCarriers() { return this.r.getCarriers(); } }
export class MarketingService { constructor(r) { this.r = r; } getCampaigns(q) { return this.r.getCampaigns(q); } getCampaign(id) { return this.r.getCampaign(id); } createCampaign(d) { return this.r.createCampaign(d); } updateCampaign(id, d) { return this.r.updateCampaign(id, d); } deleteCampaign(id) { return this.r.deleteCampaign(id); } getCoupons() { return this.r.getCoupons(); } getCoupon(id) { return this.r.getCoupon(id); } createCoupon(d) { return this.r.createCoupon(d); } updateCoupon(id, d) { return this.r.updateCoupon(id, d); } deleteCoupon(id) { return this.r.deleteCoupon(id); } }
export class CmsService { constructor(r) { this.r = r; } getContents(q) { return this.r.getContents(q); } getContent(id) { return this.r.getContent(id); } createContent(d) { return this.r.createContent(d); } updateContent(id, d) { return this.r.updateContent(id, d); } deleteContent(id) { return this.r.deleteContent(id); } getHeroSlides() { return this.r.getHeroSlides(); } createHeroSlide(d) { return this.r.createHeroSlide(d); } updateHeroSlide(id, d) { return this.r.updateHeroSlide(id, d); } deleteHeroSlide(id) { return this.r.deleteHeroSlide(id); } getGallery() { return this.r.getGallery(); } createGallery(d) { return this.r.createGallery(d); } updateGallery(id, d) { return this.r.updateGallery(id, d); } deleteGallery(id) { return this.r.deleteGallery(id); } getTestimonials() { return this.r.getTestimonials(); } createTestimonial(d) { return this.r.createTestimonial(d); } updateTestimonial(id, d) { return this.r.updateTestimonial(id, d); } deleteTestimonial(id) { return this.r.deleteTestimonial(id); } }
export class SettingsService { constructor(r) { this.r = r; } getCompany() { return this.r.getCompany(); } updateCompany(d) { return this.r.updateCompany(d); } }
export class AnalyticsService { constructor(r) { this.r = r; } getKpis() { return this.r.getKpis(); } }
export class AuditService { constructor(r) { this.r = r; } getLogs(q) { return this.r.getLogs(q); } }
export class CrmService { constructor(r) { this.r = r; } getClients(q) { return this.r.getClients(q); } getClient(id) { return this.r.getClient(id); } createClient(d) { return this.r.createClient(d); } updateClient(id, d) { return this.r.updateClient(id, d); } addNote(id, d) { return this.r.addNote(id, d); } }
export class AuthService { constructor(r) { this.r = r; } login(e, p) { return this.r.login(e, p); } getProfile() { return this.r.getProfile(); } }
